### ISSUE TITLE
Remove() breaks expiration

### ISSUE THREAD

**Issue by sb10** [diegobernardes/ttlcache#3]
Hi, this looks really promising, but has some unexpected behaviour:

```
    cache = ttlcache.NewCache()
    cache.SetExpirationCallback(func(key string, value interface{}) {
        fmt.Printf("This key(%s) has expired\n", key)
    })

    cache.SetWithTTL("keyWithTTL", "value", time.Duration(2 * time.Second))
    cache.Set("key", "value")
    //result = cache.Remove("key")

    value, exists = cache.Get("keyWithTTL")
    if exists {
        fmt.Printf("got %s for keyWithTTL\n", value)
    }
    count = cache.Count()
    fmt.Printf("cache has %d keys\n", count)

    <-time.After(3 * time.Second)

    value, exists = cache.Get("keyWithTTL")
    if exists {
        fmt.Printf("got %s for keyWithTTL\n", value)
    } else {
        fmt.Println("keyWithTTL has gone")
    }
    count = cache.Count()
    fmt.Printf("cache has %d keys\n", count)
```

The above prints:

> got value for keyWithTTL
> cache has 2 keys
> This key(keyWithTTL) has expired
> keyWithTTL has gone
> cache has 1 keys

as expected. But if you uncomment the Remove() call, you get:

> got value for keyWithTTL
> cache has 1 keys
> keyWithTTL has gone
> cache has 1 keys

so it's in some weird inconsistent state, where you can't get the key, but Count() suggests it's there, and the ExpirationCallback never fired.

**Comment by diegobernardes** [comment]
Sorry guys, this package is with some serious trouble and i didn't got time yet to fix, does anyone want to send a PR?

Also, this package don't fit my requirement speed anymore, i'm working with a new project, not released yet that has almost zero gc overhead.

If you guys really need something ready to use, there is others caches [here](https://github.com/avelino/awesome-go#data-structures)

**Comment by sb10** [comment]
I'm interested in your new project; can you post back here when you've released something?
As for now, I've written code based on ttlcache but possibly too diverged to generate a PR. I know I fixed the issues I saw in ttlcache, but it was so long ago I can't remember what the fixes were.

**Comment by diegobernardes** [comment]
Sure! 

About your code, if you don't mind you could submit the way it is. My package is already broken, so, if you fixed it's better then stays this way.

**Comment by sb10** [comment]
Unfortunately my code does something quite different to what ttlcache is supposed to do, so it's by no means a drop-in replacement. You can look at it here: https://github.com/VertebrateResequencing/wr/blob/master/queue/queue.go ; the commit history may be informative with regard to my fixes, but I don't have time to figure it out myself right now.
