### ISSUE TITLE
Remove() causes panic: runtime error: index out of range

### ISSUE THREAD

**Issue by sb10** [diegobernardes/ttlcache#4]
This:

```
cache = ttlcache.NewCache()
cache.Set("key", "value")
//cache.Remove("key")
count = cache.Count()
fmt.Printf("cache has %d keys\n", count)
```

prints this:

> cache has 1 keys

But if you uncomment the Remove() call, you get this:

> panic: runtime error: index out of range
> goroutine 1 [running]:
> panic(0x76ed00, 0xc820014120)
>     /software/vertres/installs/go/src/runtime/panic.go:464 +0x3e6
> github.com/diegobernardes/ttlcache.priorityQueue.Swap(0x0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff)
>     /nfs/users/nfs_s/sb10/src/go/src/github.com/diegobernardes/ttlcache/priority_queue.go:54 +0x1f9
> github.com/diegobernardes/ttlcache.(_priorityQueue).Swap(0xc8200d8020, 0x0, 0xffffffffffffffff)
>     <autogenerated>:3 +0xaa
> container/heap.Remove(0x7f595f9ac750, 0xc8200d8020, 0x0, 0x0, 0x0)
>     /software/vertres/installs/go/src/container/heap/heap.go:74 +0x6c
> github.com/diegobernardes/ttlcache.(_priorityQueue).remove(0xc8200d8020, 0xc8200e0000)
>     /nfs/users/nfs_s/sb10/src/go/src/github.com/diegobernardes/ttlcache/priority_queue.go:35 +0x56
> github.com/diegobernardes/ttlcache.(*Cache).Remove(0xc8200de000, 0x7daeb8, 0x3, 0x6dd860)
>     /nfs/users/nfs_s/sb10/src/go/src/github.com/diegobernardes/ttlcache/cache.go:167 +0xed
> [...]

**Comment by huangpeizhi** [comment]
I've had this problem too.

panic: runtime error: index out of range

goroutine 12 [running]:
panic(0x826680, 0xc82000a0d0)
        C:/Go/src/runtime/panic.go:481 +0x3e6
github.com/diegobernardes/ttlcache.priorityQueue.Swap(0x0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff)
        d:/workspace/src/github.com/diegobernardes/ttlcache/priority_queue.go:54 +0x1f9
github.com/diegobernardes/ttlcache.(*priorityQueue).Swap(0xc82000e2e0, 0x0, 0xffffffffffffffff)
        <autogenerated>:3 +0xaa
container/heap.Remove(0x7f74086d5118, 0xc82000e2e0, 0x0, 0x0, 0x0)
        C:/Go/src/container/heap/heap.go:74 +0x6c
github.com/diegobernardes/ttlcache.(*priorityQueue).remove(0xc82000e2e0, 0xc8203bfcc0)
        d:/workspace/src/github.com/diegobernardes/ttlcache/priority_queue.go:35 +0x56
github.com/diegobernardes/ttlcache.(*Cache).Remove(0xc8201241e0, 0xc820495330, 0x9, 0x0)
        d:/workspace/src/github.com/diegobernardes/ttlcache/cache.go:167 +0xed
main.(*Factory).Put(0xc820014380, 0x0, 0x0)
        d:/workspace/src/m-services/m-fence/factory.go:120 +0x460
main.(*Factory).DeliveLoop(0xc820014380)
        d:/workspace/src/m-services/m-fence/factory.go:100 +0x30
created by main.main
        d:/workspace/src/m-services/m-fence/main.go:34 +0x5e9

**Comment by ganesh-karthick** [comment]
Encountered the same problem, steps to reproduce

1. Add cache key, value
2. Remove key from cache
3. Get removed key from cache

The cache panics

`panic(0x6ec440, 0xc820016050)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/diegobernardes/ttlcache.priorityQueue.Swap(0x0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff)
	/Users/ganeraje/Documents/git/goworkspace/src/github.com/diegobernardes/ttlcache/priority_queue.go:54 +0x1f9
github.com/diegobernardes/ttlcache.(*priorityQueue).Swap(0xc8201b11c0, 0x0, 0xffffffffffffffff)
	<autogenerated>:3 +0xaa
container/heap.Remove(0xfc4688, 0xc8201b11c0, 0x0, 0x0, 0x0)`

**Comment by diegobernardes** [comment]
Sorry guys, this package is with some serious trouble and i didn't got time yet to fix, does anyone want to send a PR?

Also, this package don't fit my requirement speed anymore, i'm working with a new project, not released yet that has almost zero gc overhead.

If you guys really need something ready to use, there is others caches [here](https://github.com/avelino/awesome-go#data-structures)
